#Courtesy: https://github.com/magit/magit/blob/master/.travis.yml

language: generic
os: linux
dist: xenial

env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
    - GHRAW="https://raw.githubusercontent.com"
  jobs:
    - EMACS_VERSION=25.1
    # 25.2 is identical to 25.3 except for a critical security bug in
    # enriched text mode (see Emacs Bug#28350).
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1   # Debian is on this version.
    - EMACS_VERSION=26.3
    - EMACS_VERSION=27.1   # 27.1, emacs-27 branch, latest stable release 
    - EMACS_VERSION=master # 28.0.50, master branch, built daily

jobs:
  allow_failures:
    - env: EMACS_VERSION=master

install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version
  - $CURL -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python 
  - make install

script:
  - make lint 

notifications:
  email:
    # Default is change, but that includes a new branch's 1st success.
    on_success: never
    on_failure: always # The default.
